theme: jekyll-theme-cayman
title: Bienvenue chez logic fabric !
description: logic fabric est un atelier de développement web. Pour vos sites, landing pages et web apps en Python / Django / Flask, HTML / CSS et JavaScript / Vue.js.
